
# @host = http://localhost:3002
# @host = http://localhost:3002
@host = http://51.8.197.1
@service-prefix = catalog-service
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJlZTdlNjkwNy0zOTUxLTRhMjYtYTYyMC1kMDVhOWQyMDIyZjQiLCJpYXQiOjE3MTYxNjYyNjMsImV4cCI6MTcxNjI1MjY2M30.c-EHBvz-QxsFUWNlMMONbLZSQwkzaXapcOrfnHRX7NI


# @name get-products
GET {{host}}/{{service-prefix}}/products

### 

# @name get-product-by-id
GET {{host}}/{{service-prefix}}/products/0c3c1658-c9e5-42a0-b87b-3d9a7dfe07ac

### 

# @name create-product
POST {{host}}/{{service-prefix}}/products
content-type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "Batata Rustica",
  "description": "Batata Rustica",
  "price": 0.1,
  "category": "SIDE_DISH"
}

### 

# @name edit-product
PUT {{host}}/{{service-prefix}}/products/0b612db0-d081-4df4-a564-28ac04cd1cfe
content-type: application/json

{
  "name": "hamburguer de costela 2",
  "price": 20,
  "description": "hamburguer de costela",
  "category": "DESSERT"
}

### 

# @name inactive-product
DELETE {{host}}/{{service-prefix}}/products/0b612db0-d081-4df4-a564-28ac04cd1cfe
content-type: application/json

